version: '3'
services:
  database:
    image: postgres:11
    environment:
      POSTGRES_DB: zzz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - "5432:5432"
volumes:
  database-data: