spring:
  application:
    name: zzz
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api

ms-zzz:
  app:
    season: "season_2021_2022"
    lzvcup-base-url: "https://lzvcup.be"
  web:
    allowed-origins:
      - ${ALLOWED_ORIGIN_1}
      - ${ALLOWED_ORIGIN_2}
