spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/zzz"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8080

ms-zzz:
  web:
    allowed-origins:
      - "http://localhost:4200"
      - "http://localhost:8000"
