spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/zzz"
    username: postgres
    password: postgres

ms-zzz:
  web:
    allowed-origins:
      - "http://localhost:4200"
      - "http://localhost:8000"
