spring:
  application:
    name: zzz
  datasource:
    # H2
    driver-class-name: org.h2.Driver
    # Postgres
    #driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        # H2
        dialect: org.hibernate.dialect.H2Dialect
        # Postgres
        #dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api

ms-zzz:
  app:
    season: "season_2022_2023"
    lzvcup-base-url: "https://lzvcup.be"
  web:
    allowed-origins:
