spring:

  datasource:
    # Postgres with Testcontainers
    #driver-class-name: "org.testcontainers.jdbc.ContainerDatabaseDriver"
    #url: "jdbc:tc:postgresql:11:///access-control"
    # H2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:zzz"

  test:
    database:
      replace: none

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
